swagger: '2.0'
info:
  description: 'Service for geolocation solutions from Brazil.'
  version: 1.0.0
  title: 'Vue Google Maps API'
  host: 
basePath: ""
tags:
- name: Vue Google Maps
  description: All covenants
schemes:
- http
paths:
  "/gis/contratantes":
    get:
      tags:
      - Covenants
      summary: Finds the Covenants
      description: Returns 'covenant' to the caller
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: Success
          schema:
            description: convenios
            type: array
            items:
               $ref: "#/definitions/covenants"
        '400':
          description: Invalid status value   
  "/gis/transacoes":
    post:
      tags:
      - Transactions
      summary: Add transactions
      description: Add 'transactions' to the caller
      parameters:
        - in: body
          name: body
          description: The user to transaction.
          required: false
          application/json:
          schema:
            items:
              $ref: "#/components/transactions"
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                type: string
                example: _id
        '400':
          description: Invalid status value  
    get:
      tags:
      - Transactions
      summary: Find transactions
      description: Returns 'transactions' to the caller
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: Success
          schema:
            description: transactions
            type: array
            items:
               $ref: "#/definitions/transactions"
        '400':
          description: Invalid status value  
  "/gis/transacoes/{IdLoja}":
    get:
      tags:
      - Transactions
      summary: Find transactions by ID
      description: Returns 'transactions' to the caller
      parameters:
        - in: path
          name: IdLoja
          schema:
            type: integer
          required: true
          description: Numeric ID of the store to get
      responses:
        "200":
          description: Success
          schema:
            description: transactions
            type: array
            items:
               $ref: "#/definitions/transactions"
        '400':
          description: Invalid status value   

definitions:
  covenants:
    required:
      - IDLOJA
      - DESCRICAOEXIBIVELCLIENTE
      - LOGRADOURO
      - NUMERO
      - BAIRRO
      - CIDADE
      - ESTADO
      - CEP
      - LATITUDE
      - LONGITUDE
      - _id
    properties:
      IDLOJA:
        type: number
      DESCRICAOEXIBIVELCLIENTE:
        type: string
      LOGRADOURO:
        type: string
      NUMERO:
        type: string
      BAIRRO:
        type: string
      CIDADE:
        type: string
      ESTADO:
        type: string
      CEP:
        type: string
      LATITUDE:
        type: number
      LONGITUDE:
        type: number    
      _id:
        type: string  
  transactions:
    required:
      - IDLOJA
      - ADDRESS
      - _id
    properties:
      IDLOJA:
        type: number
      ADDRESS:
        type: string  
      _id:
        type: string  
        
components:       
  transactions: 
    required:
      - IDLOJA
      - ADDRESS
    properties:
      IDLOJA:
        type: number
      ADDRESS:
        type: string         